# -*- coding: utf-8 -*-
"""data_viz_scale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqaz9ny15z96CPSc3zXOdhHI4RYgdZri

# Scale Data Visualization

Visualizes **Scale** bimanual teleoperation episodes from the EgoVerse dataset.

Three visualization modes are available:

| Mode | What it shows |
|---|---|
| `traj` | End-effector trajectory projected onto the camera image |
| `axes` | YPR rotation axes drawn at each EE pose |
| `annotations` | Language annotation text overlaid per frame |

Output is an `.mp4` saved locally and displayed inline.

## 1. Install Dependencies

Clone [GaTech-RL2/EgoVerse](https://github.com/GaTech-RL2/EgoVerse) and install the `egomimic` package. **Run this cell once per runtime.**
"""

# Commented out IPython magic to ensure Python compatibility.
import os

REPO_URL = "https://github.com/GaTech-RL2/EgoVerse.git"
REPO_DIR = "/content/EgoVerse"

if not os.path.exists(REPO_DIR):
    !git clone --recursive {REPO_URL} {REPO_DIR}

# %cd {REPO_DIR}

# Install EgoVerse package without pulling its heavy robotics deps
!pip install -e . -q --no-deps

# Minimal dependencies used by this notebook
!pip install -q zarr==3.1.5 sqlalchemy "psycopg[binary]" pyquaternion simplejpeg "cloudpathlib[s3]" overrides einops rich imageio-ffmpeg projectaria-tools pytorch_kinematics scaleapi

"""## 2. Install `s5cmd`

`s5cmd` is a fast S3/R2 CLI used to sync episode data. It is not available via pip so we download the binary directly.
"""

import urllib.request, json as _json

# Fetch the latest s5cmd release URL dynamically
_api = _json.loads(urllib.request.urlopen(
    'https://api.github.com/repos/peak/s5cmd/releases/latest'
).read())
_url = next(
    a['browser_download_url'] for a in _api['assets']
    if 'linux' in a['name'].lower() and '64' in a['name'] and a['name'].endswith('.tar.gz')
)
print(f"Downloading {_url}")
!wget -q {_url} -O s5cmd.tar.gz
!tar -xzf s5cmd.tar.gz s5cmd
!mv s5cmd /usr/local/bin/s5cmd
!chmod +x /usr/local/bin/s5cmd
!s5cmd version

"""## 3. Credentials

Run this cell as-is — it uses the **public read-only AWS credentials** from the EgoVerse README
to fetch the DB secret ARN and R2 keys automatically from Secrets Manager.

If you have your own AWS credentials, add them as Colab Secrets (🔑 sidebar):

| Secret name | Description |
|---|---|
| `AWS_ACCESS_KEY_ID` | Your AWS access key (overrides the public key) |
| `AWS_SECRET_ACCESS_KEY` | Your AWS secret key (overrides the public key) |

"""

import boto3, json, os
from pathlib import Path
from tqdm.auto import tqdm

# Use personal AWS credentials from Colab Secrets if available,
# otherwise fall back to the public read-only keys from the EgoVerse README.
try:
    from google.colab import userdata
    aws_key    = userdata.get("AWS_ACCESS_KEY_ID")
    aws_secret = userdata.get("AWS_SECRET_ACCESS_KEY")
except Exception:
    aws_key = aws_secret = None

if not aws_key or not aws_secret:
    print("Using public read-only EgoVerse credentials.")
    aws_key    = os.environ.get("AWS_ACCESS_KEY_ID", "")
    aws_secret = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

os.environ["AWS_ACCESS_KEY_ID"]     = aws_key
os.environ["AWS_SECRET_ACCESS_KEY"] = aws_secret
os.environ["AWS_DEFAULT_REGION"]    = "us-east-2"

REGION = "us-east-2"
sm = boto3.client("secretsmanager", region_name=REGION)

# Resolve DB secret ARN (try private, fall back to public read-only)
secrets_arn = ""
for db_name in ["rds/appdb/appuser", "rds/appdb/appuser-readonly"]:
    try:
        secrets_arn = sm.describe_secret(SecretId=db_name)["ARN"]
        print(f"DB secret:  {db_name}")
        break
    except Exception:
        pass

# Fetch R2 credentials (try private, fall back to public)
r2_json = None
for r2_name in ["r2/rldb/credentials", "r2/rldb/public/credentials"]:
    try:
        r2_json = json.loads(sm.get_secret_value(SecretId=r2_name)["SecretString"])
        print(f"R2 secret:  {r2_name}")
        break
    except Exception:
        pass

if r2_json is None:
    raise RuntimeError("Could not fetch R2 credentials from Secrets Manager.")

# Write all resolved credentials to ~/.egoverse_env
env_lines = []
if secrets_arn:
    env_lines.append(f"SECRETS_ARN={secrets_arn}")
env_lines += [
    f"R2_ACCESS_KEY_ID={r2_json['access_key_id']}",
    f"R2_SECRET_ACCESS_KEY={r2_json['secret_access_key']}",
    f"AWS_ENDPOINT_URL_S3={r2_json['endpoint_url']}",
    f"R2_ENDPOINT_URL={r2_json['endpoint_url']}",
    f"S3_ENDPOINT_URL={r2_json['endpoint_url']}",
    f"AWS_DEFAULT_REGION={REGION}",
    "BUCKET=rldb",
]
if r2_json.get("session_token"):
    env_lines.append(f"R2_SESSION_TOKEN={r2_json['session_token']}")

env_path = Path("~/.egoverse_env").expanduser()
env_path.write_text("\n".join(env_lines))
env_path.chmod(0o600)
print(f"\n✅ Credentials written to {env_path}")

"""## 4. Configuration

- **`LOCAL_DIR`** — where zarr episodes are cached. Uses `/content/` by default (ephemeral). Mount Google Drive and set a Drive path for persistence across sessions.
- **`N`** — number of Scale episodes to download and visualize.
- **`MODE`** — visualization mode: `"traj"`, `"axes"`, or `"annotations"`.
"""

# Optional: mount Google Drive for persistent storage
# from google.colab import drive
# drive.mount("/content/drive")

LOCAL_DIR = "/content/scale_cache"
N    = 5
MODE = "traj"

"""## 5. Imports"""

from pathlib import Path
from typing import Literal

import imageio
import imageio_ffmpeg
import numpy as np
import torch

from egomimic.rldb.embodiment.embodiment import EMBODIMENT
from egomimic.rldb.embodiment.human import Scale
from egomimic.rldb.filters import DatasetFilter
from egomimic.utils.aws.aws_sql import create_default_engine, episode_table_to_df
from egomimic.rldb.zarr.action_chunk_transforms import (
    ConcatKeys,
    InterpolatePose,
    XYZWXYZ_to_XYZYPR,
)
from egomimic.rldb.zarr.zarr_dataset_multi import (
    LocalEpisodeResolver,
    MultiDataset,
    S3EpisodeResolver,
)
from egomimic.utils.aws.aws_data_utils import load_env
from egomimic.utils.viz_utils import _viz_annotations

# Zarr metadata stores short embodiment names (e.g. "SCALE") that the
# EMBODIMENT enum doesn't recognize. Patch it to accept them.
for _short in ("SCALE", "MECKA", "EVA", "ARIA", "EVE"):
    _bimanual = f"{_short}_BIMANUAL"
    if _short not in EMBODIMENT.__members__ and _bimanual in EMBODIMENT.__members__:
        EMBODIMENT._member_map_[_short] = EMBODIMENT[_bimanual]

print("Imports OK.")

from IPython.display import HTML
import base64

def show_video(path, width=720):
    """Embed an mp4 as an inline Colab video player."""
    data = Path(path).read_bytes()
    b64  = base64.b64encode(data).decode()
    return HTML(
        f'<video width="{width}" controls autoplay loop muted>'
        f'<source src="data:video/mp4;base64,{b64}" type="video/mp4">'
        f'</video>'
    )

"""## 6. List Available Episodes

Query the database for processed Scale episodes. Requires `SECRETS_ARN` to be set.

> **No DB access?** Skip this cell and the download cell — use the **Episode hashes (no DB)** cell instead.
"""

load_env()
try:
    engine = create_default_engine()
    df = episode_table_to_df(engine)

    scale_df = df[
        df["embodiment"].str.contains("SCALE", case=False, na=False)
        & df["zarr_processed_path"].notna()
        & (df["zarr_processed_path"].str.strip() != "")
    ].head(N)

    hashes = scale_df["episode_hash"].tolist()
    print(f"Found {len(scale_df)} processed Scale episodes:")
    display(scale_df[["episode_hash", "task", "num_frames"]])
except RuntimeError as e:
    print(f"DB unavailable ({e})")
    print("Set hashes manually in the next cell.")
    hashes = []

"""### Episode hashes (no DB)

If the DB query above failed, paste your episode hashes here and run this cell instead of the download cell below.
"""

# Uncomment and fill in hashes if you are skipping the DB query.
hashes = [
    "2026-03-19-01-26-48-247852",
    "2026-03-18-22-53-54-620571",
]

"""## 7. Download Episodes

Sync the selected episodes from R2 to the local cache. Already-cached episodes are skipped.
"""

if not hashes:
    raise RuntimeError("No episode hashes available. Either run the DB query cell or fill in hashes manually.")

filters = DatasetFilter(
    filter_lambdas=[f"lambda row: row['episode_hash'] in {set(hashes)!r}"]
)

print(f"Downloading {len(hashes)} episodes to '{LOCAL_DIR}'...")
S3EpisodeResolver.sync_from_filters(
    bucket_name="rldb",
    filters=filters,
    local_dir=Path(LOCAL_DIR),
)
print("Done.")

"""## 8. Visualize

The transform pipeline converts raw zarr poses into a format the renderer understands:

1. **World → camera frame** — EE poses are stored in world frame. `obs_head_pose` (the Aria headset pose) is used to rotate them into camera frame, so they project correctly onto the image.
2. **Interpolate** each arm's action chunk to a fixed 100-step horizon.
3. **Convert** quaternions (`xyzwxyz`) → YPR Euler angles.
4. **Concatenate** left + right into `actions_cartesian`.
"""

from egomimic.rldb.zarr.action_chunk_transforms import (
    ActionChunkCoordinateFrameTransform,
    DeleteKeys,
    PoseCoordinateFrameTransform,
)


def _scale_cartesian_keymap():
    """Cartesian keymap extended with obs_head_pose for the world→camera transform."""
    key_map = Scale.get_keymap(keymap_mode="cartesian")
    key_map["obs_head_pose"] = {"key_type": "proprio_keys", "zarr_key": "obs_head_pose"}
    return key_map


def _build_scale_viz_transform_list(chunk_length: int = 100) -> list:
    head       = "obs_head_pose"
    la, ra     = "left.action_ee_pose",      "right.action_ee_pose"
    lo, ro     = "left.obs_ee_pose",         "right.obs_ee_pose"
    la_c, ra_c = "left.action_ee_pose_cam",  "right.action_ee_pose_cam"
    lo_c, ro_c = "left.obs_ee_pose_cam",     "right.obs_ee_pose_cam"
    return [
        # 1. Rotate from world frame into camera frame using the headset pose.
        ActionChunkCoordinateFrameTransform(
            target_world=head, chunk_world=la, transformed_key_name=la_c, mode="xyzwxyz"),
        ActionChunkCoordinateFrameTransform(
            target_world=head, chunk_world=ra, transformed_key_name=ra_c, mode="xyzwxyz"),
        PoseCoordinateFrameTransform(
            target_world=head, pose_world=lo, transformed_key_name=lo_c, mode="xyzwxyz"),
        PoseCoordinateFrameTransform(
            target_world=head, pose_world=ro, transformed_key_name=ro_c, mode="xyzwxyz"),
        # 2. Interpolate action chunk to fixed horizon.
        InterpolatePose(new_chunk_length=chunk_length, action_key=la_c,
                        output_action_key=la_c, stride=Scale.ACTION_STRIDE, mode="xyzwxyz"),
        InterpolatePose(new_chunk_length=chunk_length, action_key=ra_c,
                        output_action_key=ra_c, stride=Scale.ACTION_STRIDE, mode="xyzwxyz"),
        # 3. Quaternion → YPR.
        XYZWXYZ_to_XYZYPR(keys=[la_c, ra_c, lo_c, ro_c]),
        # 4. Concatenate both arms.
        ConcatKeys(key_list=[la_c, ra_c], new_key_name="actions_cartesian", delete_old_keys=True),
        ConcatKeys(key_list=[lo_c, ro_c], new_key_name="observations.state.ee_pose", delete_old_keys=True),
        DeleteKeys(keys_to_delete=[la, ra, lo, ro, head]),
    ]


def visualize_scale_data(
    episode_hash: str,
    temp_dir: str,
    output_path: str | None = None,
    mode: Literal["traj", "axes", "annotations"] = "traj",
    max_frames: int = 10_000,
    fps: int = 30,
    stride: int = 1,
    sync_from_s3: bool = False,
):
    """Render a Scale episode to an mp4 and return the frames as a numpy array.

    stride: keep every Nth source frame. Output fps is adjusted to fps/stride so
            real-time playback speed is unchanged (e.g. stride=3 renders 3× faster
            and writes at 10 fps instead of 30 fps).
    """
    load_env()

    if output_path is None:
        output_path = str(Path(temp_dir) / f"{episode_hash}_{mode}.mp4")

    if mode == "annotations":
        key_map = Scale.get_keymap(keymap_mode="cartesian", annotation_key="annotations")
        transform_list, viz_batch_key = None, "annotations"
    else:
        key_map = _scale_cartesian_keymap()
        transform_list, viz_batch_key = _build_scale_viz_transform_list(), "actions_cartesian"

    filters = DatasetFilter(
        filter_lambdas=[f"lambda row: row['episode_hash'] in {set([episode_hash])!r}"]
    )
    ResolverCls = S3EpisodeResolver if sync_from_s3 else LocalEpisodeResolver
    resolver = ResolverCls(temp_dir, key_map=key_map, transform_list=transform_list)
    multi_ds = MultiDataset._from_resolver(
        resolver, filters=filters, sync_from_s3=sync_from_s3, mode="total"
    )

    # Pre-load annotation spans from zarr so we can number them (0., 1., …)
    import zarr as _zarr, json as _json
    _ann_spans: list[dict] = []
    try:
        _store = _zarr.open_group(str(Path(temp_dir) / episode_hash), mode="r")
        for _x in _store["annotations"][:]:
            if isinstance(_x, bytes):
                _x = _x.decode()
            try:
                _ann_spans.append(_json.loads(_x))
            except Exception:
                pass
    except Exception:
        pass

    def _ann_texts(frame_idx: int) -> list[str]:
        return [
            f"{idx}. {span.get('text', '')}"
            for idx, span in enumerate(_ann_spans)
            if int(span.get("start_idx", -1)) <= frame_idx < int(span.get("end_idx", -1))
        ]

    loader = torch.utils.data.DataLoader(multi_ds, batch_size=1, shuffle=False)
    total_source = min(len(multi_ds), max_frames)
    n_rendered = (total_source + stride - 1) // stride
    images = []

    try:
        from tqdm.auto import tqdm as _tqdm
        _iter = _tqdm(loader, total=total_source, desc=f"Rendering {episode_hash[:16]}…", unit="frame")
    except ImportError:
        _iter = loader

    for i, batch in enumerate(_iter):
        if i >= max_frames:
            break
        if i % stride != 0:
            continue
        vis = Scale.viz_transformed_batch(batch, mode=mode, viz_batch_key=viz_batch_key)
        texts = _ann_texts(i)
        if texts:
            vis = _viz_annotations(vis, texts)
        images.append(vis)
        n_kept = len(images)
        if n_kept % max(1, n_rendered // 20) == 0 or n_kept == n_rendered:
            print(f"\rFrame {n_kept}/{n_rendered}", end="", flush=True)
    print()

    if not images:
        raise RuntimeError(f"No frames rendered for episode '{episode_hash}'.")

    images = np.stack(images, axis=0)
    out_fps = fps / stride  # preserve real-time playback speed
    writer = imageio.get_writer(output_path, fps=out_fps)
    for frame in images:
        writer.append_data(frame)
    writer.close()

    print(f"Saved {len(images)} frames at {out_fps:.1f} fps → {output_path}")
    return images

"""### Run — single episode

Change `hashes[0]` to any episode hash from the table above.
"""

EPISODE_HASH = hashes[0]
STRIDE = 3  # render every 3rd frame → ~3× faster; output fps is adjusted automatically

output_path = Path(LOCAL_DIR) / f"{EPISODE_HASH}_{MODE}.mp4"
frames = visualize_scale_data(
    episode_hash=EPISODE_HASH,
    temp_dir=LOCAL_DIR,
    mode=MODE,
    stride=STRIDE,
    max_frames = 400
)

print('Showing video...')

show_video(output_path)

"""## 9. Export for Combined Visualization

Export the right hand EE pose and head pose data for use with `visualize_combined.py`.
This saves the data in camera-relative coordinates that match the MARS arm FK frame.
"""

import zarr as _zarr_export
import json as _json_export

def export_scale_episode(episode_hash, local_dir, output_path=None):
    """Export Scale episode data for combined visualization with MARS arm."""
    if output_path is None:
        output_path = f"{episode_hash}_export.npz"

    store = _zarr_export.open_group(str(Path(local_dir) / episode_hash), mode="r")

    # List all available keys
    print("Available zarr keys:")
    def _list_keys(group, prefix=""):
        for key in group.keys():
            item = group[key]
            if hasattr(item, 'shape'):
                print(f"  {prefix}{key}: shape={item.shape}, dtype={item.dtype}")
            else:
                _list_keys(item, prefix=f"{prefix}{key}/")
    _list_keys(store)

    # Load right hand EE pose and head pose
    right_ee = np.array(store["right"]["obs_ee_pose"][:])
    head_pose = np.array(store["obs_head_pose"][:])

    print(f"\nRight EE pose shape: {right_ee.shape}")
    print(f"Head pose shape: {head_pose.shape}")

    # Transform to camera frame
    from pyquaternion import Quaternion as Q
    T = min(len(right_ee), len(head_pose))
    right_ee_cam = np.zeros((T, 3))

    for t in range(T):
        head_pos = head_pose[t, :3]
        head_q = Q(head_pose[t, 3], head_pose[t, 4], head_pose[t, 5], head_pose[t, 6])
        ee_pos = right_ee[t, :3]
        displacement = ee_pos - head_pos
        right_ee_cam[t] = head_q.inverse.rotate(displacement)

    np.savez(output_path,
             right_ee_cam=right_ee_cam,
             right_ee_world=right_ee[:T],
             head_poses=head_pose[:T],
             fps=30)

    print(f"\nExported {T} frames to {output_path}")
    print("Download this file and run:")
    print(f"  python visualize_combined.py --scale-data {output_path}")

    return output_path

# Export the episode we just visualized
export_path = export_scale_episode(EPISODE_HASH, LOCAL_DIR)

"""## 10. Browse & Select Episodes for Training

Query the full database, browse available tasks, and select 100 episodes
for cross-embodiment training with the MARS robot.
"""

load_env()
engine = create_default_engine()
df_all = episode_table_to_df(engine)

# Filter to processed Scale episodes only
scale_all = df_all[
    df_all["embodiment"].str.contains("SCALE", case=False, na=False)
    & df_all["zarr_processed_path"].notna()
    & (df_all["zarr_processed_path"].str.strip() != "")
].copy()

print(f"Total processed Scale episodes: {len(scale_all)}")
print(f"\n--- Available tasks ---")
task_counts = scale_all["task"].value_counts()
display(task_counts)

print(f"\n--- Available columns ---")
print(scale_all.columns.tolist())

"""### 10a. Filter by task

Adjust the filters below to select episodes relevant to your robot.
MARS has a single arm + gripper, so single-arm grasping/placing tasks are the best match.
"""

# ---- EDIT THESE FILTERS ----
# Option 1: Select specific tasks by keyword
TASK_KEYWORDS = []  # e.g. ["pick", "place", "grasp", "container", "cup"]

# Option 2: Exclude tasks by keyword
EXCLUDE_KEYWORDS = []  # e.g. ["bimanual", "bag"]

# Option 3: Min/max episode length (frames)
MIN_FRAMES = 30
MAX_FRAMES = 5000

# Number of episodes to select
N_EPISODES = 100
# ---- END FILTERS ----

selected = scale_all.copy()

# Apply task keyword filter
if TASK_KEYWORDS:
    pattern = "|".join(TASK_KEYWORDS)
    selected = selected[selected["task"].str.contains(pattern, case=False, na=False)]
    print(f"After task keyword filter ({TASK_KEYWORDS}): {len(selected)} episodes")

# Apply exclude filter
if EXCLUDE_KEYWORDS:
    pattern = "|".join(EXCLUDE_KEYWORDS)
    selected = selected[~selected["task"].str.contains(pattern, case=False, na=False)]
    print(f"After exclude filter ({EXCLUDE_KEYWORDS}): {len(selected)} episodes")

# Apply frame count filter
if "num_frames" in selected.columns:
    selected = selected[
        (selected["num_frames"] >= MIN_FRAMES) &
        (selected["num_frames"] <= MAX_FRAMES)
    ]
    print(f"After frame count filter ({MIN_FRAMES}-{MAX_FRAMES}): {len(selected)} episodes")

# Sample N episodes (stratified by task if possible)
if len(selected) > N_EPISODES:
    # Try stratified sampling: proportional episodes per task
    try:
        selected = selected.groupby("task", group_keys=False).apply(
            lambda x: x.sample(n=max(1, int(len(x) / len(selected) * N_EPISODES)),
                               random_state=42)
        ).head(N_EPISODES)
    except Exception:
        selected = selected.sample(n=N_EPISODES, random_state=42)

print(f"\n=== Selected {len(selected)} episodes ===")
print(f"\nTask distribution:")
display(selected["task"].value_counts())

if "num_frames" in selected.columns:
    print(f"\nFrame count stats:")
    print(f"  Min: {selected['num_frames'].min()}")
    print(f"  Max: {selected['num_frames'].max()}")
    print(f"  Mean: {selected['num_frames'].mean():.0f}")
    print(f"  Total: {selected['num_frames'].sum()}")

training_hashes = selected["episode_hash"].tolist()
print(f"\nSelected hashes: {len(training_hashes)}")

"""### 10b. Download selected episodes

This may take a while for 100 episodes. Already-cached episodes are skipped.
"""

if not training_hashes:
    raise RuntimeError("No episodes selected. Adjust filters above.")

filters = DatasetFilter(
    filter_lambdas=[f"lambda row: row['episode_hash'] in {set(training_hashes)!r}"]
)

print(f"Downloading {len(training_hashes)} episodes to '{LOCAL_DIR}'...")
S3EpisodeResolver.sync_from_filters(
    bucket_name="rldb",
    filters=filters,
    local_dir=Path(LOCAL_DIR),
)
print("Download complete.")

"""### 10c. Batch export for ACT training

Export all selected episodes as .npz files, then download them to use with
`convert_to_shared_dataset.py` on your local machine.
"""

import simplejpeg
from tqdm.auto import tqdm

EXPORT_DIR = "/content/scale_exports"
os.makedirs(EXPORT_DIR, exist_ok=True)

def export_episode_for_training(episode_hash, local_dir, export_dir):
    """Export a single episode with EE poses, head pose, and camera frames."""
    output_path = os.path.join(export_dir, f"{episode_hash}.npz")
    if os.path.exists(output_path):
        return output_path  # skip if already exported

    try:
        store = _zarr_export.open_group(str(Path(local_dir) / episode_hash), mode="r")
    except Exception as e:
        print(f"  SKIP {episode_hash}: {e}")
        return None

    try:
        right_ee = np.array(store["right"]["obs_ee_pose"][:])
        head_pose = np.array(store["obs_head_pose"][:])
    except KeyError as e:
        print(f"  SKIP {episode_hash}: missing key {e}")
        return None

    T = min(len(right_ee), len(head_pose))

    # Transform EE to camera frame
    from pyquaternion import Quaternion as Q
    right_ee_cam = np.zeros((T, 3))
    for t in range(T):
        h_pos = head_pose[t, :3]
        h_q = Q(head_pose[t, 3], head_pose[t, 4], head_pose[t, 5], head_pose[t, 6])
        disp = right_ee[t, :3] - h_pos
        right_ee_cam[t] = h_q.inverse.rotate(disp)

    # Try to load camera frames
    images = None
    try:
        if "rgb" in store:
            raw_imgs = store["rgb"][:]
            images = np.zeros((T, 224, 224, 3), dtype=np.uint8)
            for t in range(T):
                if isinstance(raw_imgs[t], bytes):
                    img = simplejpeg.decode_jpeg(raw_imgs[t])
                else:
                    img = np.array(raw_imgs[t])
                if img.shape[:2] != (224, 224):
                    import cv2
                    img = cv2.resize(img, (224, 224))
                images[t] = img
    except Exception as e:
        print(f"  Warning: could not load images for {episode_hash}: {e}")

    save_dict = {
        "right_ee_cam": right_ee_cam,
        "right_ee_world": right_ee[:T],
        "head_poses": head_pose[:T],
        "fps": 30,
        "episode_hash": episode_hash,
    }
    if images is not None:
        save_dict["images"] = images

    np.savez_compressed(output_path, **save_dict)
    return output_path


print(f"Exporting {len(training_hashes)} episodes to {EXPORT_DIR}...")
exported = []
failed = []

for h in tqdm(training_hashes, desc="Exporting"):
    result = export_episode_for_training(h, LOCAL_DIR, EXPORT_DIR)
    if result:
        exported.append(result)
    else:
        failed.append(h)

print(f"\n=== Export complete ===")
print(f"  Exported: {len(exported)}")
print(f"  Failed:   {len(failed)}")
if failed:
    print(f"  Failed hashes: {failed[:10]}{'...' if len(failed) > 10 else ''}")

# Calculate total size
total_size = sum(os.path.getsize(p) for p in exported)
print(f"  Total size: {total_size / 1e9:.2f} GB")

"""### 10d. Download exports

Download the exported .npz files to your local machine, then run:

```bash
python convert_to_shared_dataset.py scale \\
    --input-dir /path/to/downloaded/scale_exports/ \\
    --output-dir /path/to/shared_dataset/
```

Or zip them first for a single download:
"""

!cd {EXPORT_DIR} && tar -czf /content/scale_training_export.tar.gz *.npz
print(f"\nCompressed archive: /content/scale_training_export.tar.gz")
print("Download this file, extract, and run convert_to_shared_dataset.py")

from google.colab import files
files.download("/content/scale_training_export.tar.gz")